POST  http://localhost:3333/courses
Content-Type: application/json

{
  "title": "a"
}

###
GET http://localhost:3333/courses

###
GET http://localhost:3333/courses/aae914e8-6445-4ba8-96c4-448f023b26c1

###
DELETE http://localhost:3333/courses/df5bc0e8-4983-4ecb-a65a-4e9cd3afbfce